### ISSUE TITLE
Build.PL and Makefile.PL

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_perl#7]
The README.md file gives instructions about using `Build.PL` but there's also a `Makefile.PL` which I understand produces a Makefile. Are them alternative build scripts ? Should either one be removed ? 

Same question applies to linz_utils_perl ...

**Comment by palmerj** [comment]
Makefile has been provided a compatibility with ExtUtils::MakeMaker for the distribution so `make xxx` is possible. Makefile.PL was automatically generated using `Build create_makefile_pl`.

**Comment by strk** [comment]
Would it make sense to *remove* the generated Makefile.PL from the repository then ?

**Comment by palmerj** [comment]
No it's in just a convenience wrapper for GNU make people, so it's doesn't need to be regenerated each time the build script is.

**Comment by strk** [comment]
I understand, but for GNU make people it currently still takes an additional step (running `perl Makefile.pl`) so I guess it could be made even simpler, having a Makefile which would call `perl Makefile.pl` by default, and remove from the repository what can be generated when needed.

Anyway, when I tried this approach, I failed generating the `Makefile.PL` using `./Build create_makefile_pl`
with error:
```
No action 'create_makefile_pl' defined, try running the 'help' action.
```
This was after I removed `Makefile.PL` and run `perl Build.PL` again, which also warned:
```
WARNING: the following files are missing in your kit:
        Makefile.PL
Please inform the author.
```

This article from May 2015 reports seems interesting:
http://neilb.org/2015/05/18/two-build-files-considered-harmful.html

According to one of the commentors, Makefile.PL should be generated from Build.PL instead of made part of the distribution.

**Comment by strk** [comment]
PR #10 removes the generated `Makefile.PL` from the git repository, generating it on `./configure` for those who like GNU standard build interface
