### ISSUE TITLE
Document how to install from packages, if any

### ISSUE THREAD

**Issue by strk** [linz/linz_bde_perl#8]
I have the impression there are binary packages available somewhere (looking at the `debian/`) subdir, so this ticket is to document how to find those packages (if anywhere publicly) for easy install.

If there are other ways (CPAN?) that's also useful to document.

**Comment by imincik** [comment]
Binary packages are built in LINZ PPA

**Comment by strk** [comment]
Is LINZ PPA public ? what's the URL ?

**Comment by strk** [comment]
From https://github.com/linz/linz_utils_perl/issues/6#issuecomment-307257238 I guess there is only private PPA ... do we want to have a public one ? Something to ticket elsewhere ?

**Comment by imincik** [comment]
LINZ PPA URL is https://{{ linz_repository_username }}:{{ linz_repository_password }}@private-ppa.launchpad.net/linz/prod/ubuntu . We don't have a public one for now.

I don't think we should document how to use LINZ PPA here. I am closing this task. If some instructions how to build binaries is missing here, create a new task please.
